#! /bin/bash
# clean up the log file generated by the training script from 'https://github.com/LeapLabTHU/MLLA'
# keep the training args, model info, training accuracy, and remove the log prefix
#
# usage:
#   sh clean_log.sh -src <source_file> -dst <destination_file>
#
# dependencies:
#   rg: https://github.com/BurntSushi/ripgrep

src=""
dst=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -src) src="$2"; shift ;;
        -dst) dst="$2"; shift ;;
        -h) echo "Usage: sh clean_log.sh -src <source_file> -dst <destination_file>"
            exit 0 ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

if [[ -z "$src" || -z "$dst" ]]; then
    echo "Usage: sh clean_log.sh -src <source_file> -dst <destination_file>"
    exit 1
fi

if [[ ! -f "$src" ]]; then
    echo "Source file not found: $src"
    exit 1
fi

# 1. get training args and model info
rg '^\)$' -m 1 $src -B 10000 -N -I | tail -n +2 > $dst

# 2. add a new line
echo "" >> $dst

# 3. get training accuracy
rg 'INFO Accuracy of the network on the 50000 test images' $src -C 2 -N -I >> $dst

# 4. remove the log prefix
#  inp: [2025-01-02 16:57:53 mlla_nano] (main.py 304): INFO EPOCH 26 training takes 0:06:17
#  oup: EPOCH 26 training takes 0:06:17
sed -i '' -E 's/^\[[^]]+\] \([^)]+\): INFO //' $dst

# 5. remove the training time
#  inp: EPOCH 26 training takes 0:06:17
#  oup: EPOCH 26
sed -i '' -E 's/ training takes [^ ]+//' $dst

